# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"POST_STATUS_MAP": "00_core.ipynb",
         "SCHEMA_SQL": "40a_service_db.ipynb",
         "ServiceDb": "40a_service_db.ipynb",
         "before_request": "40b_service_filesystem.ipynb",
         "after_request": "40b_service_filesystem.ipynb",
         "init_service": "40b_service_filesystem.ipynb",
         "posts_list_to_dict": "40b_service_filesystem.ipynb",
         "migrate": "40b_service_filesystem.ipynb",
         "ServiceFilesystem": "40b_service_filesystem.ipynb",
         "create_app": "50_web_app.ipynb",
         "login_required": "50b_web_auth.ipynb",
         "load_logged_in_user": "50b_web_auth.ipynb",
         "bp": "50c_web_blog.ipynb",
         "login": "50b_web_auth.ipynb",
         "logout": "50b_web_auth.ipynb",
         "index": "50c_web_blog.ipynb",
         "get_post": "50c_web_blog.ipynb",
         "create": "50c_web_blog.ipynb",
         "update": "50c_web_blog.ipynb",
         "delete": "50c_web_blog.ipynb",
         "download": "50c_web_blog.ipynb",
         "upload": "50c_web_blog.ipynb"}

modules = ["core.py",
           "service/db.py",
           "service/filesystem.py",
           "web/app.py",
           "web/auth.py",
           "web/blog.py"]

doc_url = "https://pete88b.github.io/web_journal/"

git_url = "https://github.com/pete88b/web_journal/tree/main/"

def custom_doc_links(name): return None
